### ISSUE TITLE
Hacks not working

### ISSUE THREAD

**Issue by VillainsRule4000** [VillainsRule2000/Betastar#3]
### Created by @FallGuysFan1234

<div type='discussions-op-text'>

<sup>Originally posted by **FallGuysFan1234** May 16, 2022</sup>
Hey @VillainsRule4000! I was trying to use the spam open crates hack and the get atoms hack, but none of them worked! I hope you are able to fix it and I will now show images of what happens when I use them :D
![image](https://user-images.githubusercontent.com/92480033/168633304-15724fd4-088c-4c6b-a588-a3e0dea92a33.png) (Using the Spam Open Crates hack here)
![image](https://user-images.githubusercontent.com/92480033/168633580-ef9c25d5-2f9f-4ee8-af46-728a0d2b26e4.png)
(Using the Get Atoms hack here and it just keeps pausing in debugger even if I stop it and it doesn't add atoms!)
Now that you've seen these images, I hope you or zastix will be able to fix these hacks :D
</div>

**Comment by VillainsRule4000** [comment]
@FallGuysFan1234 I will look into it.

**Comment by FallGuysFan1234** [comment]
> @FallGuysFan1234 I will look into it.

Ok great to hear! :D

**Comment by VillainsRule4000** [comment]
@FallGuysFan1234 A lot of people say that these scripts don't work, I can't actually confirm or deny it as every script has always worked for me. I think this was a Betastar moment, so everything should work.

I can tell you're on Chrome, but what computer? (Mac, Windows, Chromebook)

**Comment by FallGuysFan1234** [comment]
> @FallGuysFan1234 A lot of people say that these scripts don't work, I can't actually confirm or deny it as every script has always worked for me. I think this was a Betastar moment, so everything should work.
> 
> I can tell you're on Chrome, but what computer? (Mac, Windows, Chromebook)

Im on a school chromebook! :D

**Comment by FallGuysFan1234** [comment]
> @FallGuysFan1234 Your admin might have blocked a specific URL or has a policy that bans a certain feature. Try using the bookmarklet method! https://caiorss.github.io/bookmarklet-maker/

Ok! :D

**Comment by Hankypoo7** [comment]
im on a school chromebook, and it works fine for me!

**Comment by VillainsRule4000** [comment]
Yeah, it appears that it was a temporary error. If the issue persists, post a new one.
