### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by notzastix** [VillainsRule2000/Betastar#6]
Hey, thanks for crediting me, but can you stop referring to them as "my scripts" because you obviously didn't make them, thanks.

**Comment by notzastix** [comment]
Also, https://github.com/VillainsRule2000/Betastar/issues/3 was caused by him running the script twice in the same session without reloading.

**Comment by VillainsRule4000** [comment]
@notzastix Thank you for letting me know, didn't catch that mistake :/
If you would like me to take the scripts down, that's totally fine.

**Comment by notzastix** [comment]
> @notzastix Thank you for letting me know, didn't catch that mistake :/ If you would like me to take the scripts down, that's totally fine.

No, I like how you're using GitHub pages to display the hacks, keep it up!

**Comment by VillainsRule4000** [comment]
@notzastix Thanks! I appreciate your skills as a codemaker.
